#!/bin/sh
#set -e
if [ "$1" = "configure" ]; then
	chown nobody:nogroup /opt/bcn-pinger/log/
	chmod 755 /opt/bcn-pinger/webpage/readLog.cgi
	chmod 644 /opt/bcn-pinger/etc/traceroute-cron
	a2enmod cgi && a2ensite bcn-pinger && service apache2 restart
	update-rc.d bcn-pingerd defaults
fi

